"""Build Session 8E contract-aligned US label market inputs.

All writes are artifact-scoped. Existing datasets and Session 8D artifacts are
read-only inputs. Raw Yahoo chart responses are immutable gzip payloads with an
append-only request manifest; normalized prices are restricted to XNYS regular
sessions generated by a pinned exchange-calendars release.
"""
from __future__ import annotations

import argparse
import gzip
import hashlib
import importlib.metadata
import json
import os
import shutil
import subprocess
import sys
import threading
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.parse import urlencode

import numpy as np
import pandas as pd
import requests

HORIZONS = {"6m": 6, "1y": 12, "2y": 24, "3y": 36, "5y": 60}
BENCHMARKS = ("IWC", "IWM", "MDY", "SPY")
EXCHANGE_CALENDARS = {"NYSE": "XNYS", "Nasdaq": "XNAS"}
PROVIDER_EXCHANGES = {"NYSE": {"NYQ", "ASE", "PCX"}, "Nasdaq": {"NMS", "NCM", "NGM"}}
STEP2_MANIFEST_SHA256 = "899cffd7a9d1dc3395a08bee5c65ad4a5e8a109a83c63346ac54c891fe706e08"
CALENDAR_CONTRACT_SHA256 = "13cd7494aa7f0ff6e3f8a11efa0ee7a9a087968bb20b1fd5a9cb57f380148296"
SOURCE_PATH = "artifacts/pit_validation/corrected_step2/outputs/certified_snapshots.parquet"
ENDPOINT = "https://query1.finance.yahoo.com/v8/finance/chart/{symbol}"
START_DATE = "2009-07-01"
USER_AGENT = "stock-fraud-screener Session8E evidence build"


def sha256_file(path: Path, chunk_size: int = 1024 * 1024) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(chunk_size), b""):
            h.update(chunk)
    return h.hexdigest()


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def provider_symbol(ticker: str) -> str:
    """Apply the sole authorized deterministic symbol normalization."""
    return str(ticker).strip().upper().replace(".", "-")


def _epoch(date: str) -> int:
    return int(pd.Timestamp(date, tz="UTC").timestamp())


def _request_params(end_date_exclusive: str) -> dict[str, Any]:
    return {
        "period1": _epoch(START_DATE),
        "period2": _epoch(end_date_exclusive),
        "interval": "1d",
        "events": "div,splits,capitalGains",
        "includeAdjustedClose": "true",
    }


def validate_prerequisites(root: Path) -> pd.DataFrame:
    step2_manifest = root / "artifacts/pit_validation/corrected_step2/manifest.json"
    calendar_contract = root / "artifacts/pit_validation/calendar_contract/session8b_calendar_contract.json"
    if sha256_file(step2_manifest) != STEP2_MANIFEST_SHA256:
        raise RuntimeError("Session 8D manifest hash mismatch")
    if sha256_file(calendar_contract) != CALENDAR_CONTRACT_SHA256:
        raise RuntimeError("Session 8B calendar contract hash mismatch")
    source = root / SOURCE_PATH
    recorded = json.loads(step2_manifest.read_text())
    output = next(x for x in recorded["outputs"] if x["path"] == SOURCE_PATH)
    if source.stat().st_size != output["size_bytes"] or sha256_file(source) != output["sha256"]:
        raise RuntimeError("certified Step 2 source does not match Session 8D manifest")
    frame = pd.read_parquet(source)
    annual = frame.loc[frame["period_type"].eq("annual")].copy()
    if len(annual) != 43_806:
        raise RuntimeError(f"expected 43,806 certified annual rows, got {len(annual)}")
    required = {
        "entity_id", "cik", "ticker", "fiscal_year", "period_type", "market",
        "availability_timestamp", "availability_provenance", "shares_outstanding",
    }
    if not required.issubset(annual.columns):
        raise RuntimeError(f"certified annual population missing {sorted(required - set(annual.columns))}")
    return annual


def initialize(root: Path, artifact_root: Path, end_date_exclusive: str) -> None:
    if artifact_root.exists() and any(artifact_root.iterdir()):
        raise RuntimeError(f"artifact root already exists and is non-empty: {artifact_root}")
    for path in (
        "inputs", "configuration", "calendar", "raw/chart", "checkpoints",
        "normalized/prices", "normalized/events", "outputs/observed_only",
        "outputs/include_policy_imputed", "support", "lineage",
    ):
        (artifact_root / path).mkdir(parents=True, exist_ok=True)
    annual = validate_prerequisites(root)
    annual.to_parquet(artifact_root / "inputs/certified_annual_population.parquet", index=False)
    shutil.copy2(
        root / "artifacts/pit_validation/calendar_contract/session8b_calendar_contract.json",
        artifact_root / "inputs/session8b_calendar_contract.json",
    )
    symbols = sorted(set(annual["ticker"].map(provider_symbol)) | set(BENCHMARKS))
    mappings = annual[["entity_id", "cik", "ticker"]].drop_duplicates().copy()
    mappings["provider_symbol"] = mappings["ticker"].map(provider_symbol)
    mappings["mapping_policy"] = np.where(
        mappings["ticker"].astype(str).str.upper().eq(mappings["provider_symbol"]),
        "exact_uppercase", "dot_to_dash",
    )
    mappings.to_parquet(artifact_root / "inputs/security_mapping.parquet", index=False)
    config = {
        "schema_version": 1,
        "session": "8E",
        "source_population": SOURCE_PATH,
        "source_population_rows": len(annual),
        "distinct_entities": int(annual["entity_id"].nunique()),
        "distinct_provider_symbols_including_benchmarks": len(symbols),
        "endpoint": ENDPOINT,
        "request_params": _request_params(end_date_exclusive),
        "start_date": START_DATE,
        "end_date_exclusive": end_date_exclusive,
        "benchmarks": list(BENCHMARKS),
        "horizons_calendar_months": HORIZONS,
        "calendars": {**EXCHANGE_CALENDARS, "benchmarks": "XNYS"},
        "decision_size": "last regular-session raw close strictly before decision multiplied by certified decision-available shares_outstanding",
        "adjustment_policy": "source adjclose only; dividends/splits/capital gains preserved as evidence and never added separately",
        "policy_imputation": "no unsupported disappearance or corporate-action outcome inferred; separate namespace only",
        "missing_data": "fail_closed_no_substitution",
        "created_at_utc": _utc_now(),
    }
    (artifact_root / "configuration/config.json").write_text(json.dumps(config, indent=2, sort_keys=True) + "\n")
    (artifact_root / "checkpoints/symbols.json").write_text(json.dumps(symbols, indent=2) + "\n")


def freeze_calendar(artifact_root: Path) -> None:
    import exchange_calendars as xcals

    config = json.loads((artifact_root / "configuration/config.json").read_text())
    end = pd.Timestamp(config["end_date_exclusive"]) - pd.Timedelta(days=1)
    schedules = {}
    for name in sorted(set(EXCHANGE_CALENDARS.values())):
        cal = xcals.get_calendar(name)
        sessions = cal.sessions_in_range(pd.Timestamp(START_DATE), end)
        schedule = cal.schedule.loc[sessions, ["open", "close"]].reset_index()
        schedule.columns = ["session_date", "market_open", "market_close"]
        schedule["session_date"] = pd.to_datetime(schedule["session_date"]).dt.strftime("%Y-%m-%d")
        schedule.to_parquet(artifact_root / f"calendar/{name.lower()}_regular_sessions.parquet", index=False)
        schedules[name] = schedule
    aligned = schedules["XNAS"].equals(schedules["XNYS"])
    if not aligned:
        raise RuntimeError("XNYS and XNAS regular sessions differ; per-exchange normalization is required")
    config.pop("calendar", None)
    config["calendars"] = {**EXCHANGE_CALENDARS, "benchmarks": "XNYS"}
    (artifact_root / "configuration/config.json").write_text(json.dumps(config, indent=2, sort_keys=True) + "\n")
    module = Path(xcals.__file__).resolve()
    package_dir = module.parent
    source_records = []
    for path in sorted(package_dir.glob("*.py")):
        source_records.append({
            "path": str(path), "size_bytes": path.stat().st_size, "sha256": sha256_file(path),
        })
    evidence = {
        "package": "exchange-calendars",
        "version": importlib.metadata.version("exchange-calendars"),
        "module_path": str(module),
        "calendars": {
            name: {"session_count": len(frame), "first_session": frame["session_date"].min(), "last_session": frame["session_date"].max()}
            for name, frame in schedules.items()
        },
        "xnys_xnas_dates_opens_closes_identical_over_frozen_interval": aligned,
        "installed_source_records": source_records,
        "generated_at_utc": _utc_now(),
    }
    (artifact_root / "calendar/calendar_evidence.json").write_text(json.dumps(evidence, indent=2) + "\n")


_thread_local = threading.local()
_YAHOO_RATE_LOCK = threading.Lock()
_YAHOO_NEXT_REQUEST_AT = 0.0
YAHOO_REQUEST_INTERVAL_SECONDS = 0.5
YAHOO_429_COOLDOWN_SECONDS = 15.0


def _session() -> requests.Session:
    if not hasattr(_thread_local, "session"):
        s = requests.Session()
        s.headers.update({"User-Agent": USER_AGENT, "Accept": "application/json"})
        _thread_local.session = s
    return _thread_local.session


def _yahoo_rate_wait(interval_seconds: float = YAHOO_REQUEST_INTERVAL_SECONDS) -> None:
    """Globally space request starts across all Yahoo worker threads."""
    global _YAHOO_NEXT_REQUEST_AT
    while True:
        with _YAHOO_RATE_LOCK:
            now = time.monotonic()
            wait_seconds = _YAHOO_NEXT_REQUEST_AT - now
            if wait_seconds <= 0:
                _YAHOO_NEXT_REQUEST_AT = now + interval_seconds
                return
        time.sleep(wait_seconds)


def _yahoo_cooldown(seconds: float) -> None:
    """Extend the shared request gate after any worker receives HTTP 429."""
    global _YAHOO_NEXT_REQUEST_AT
    with _YAHOO_RATE_LOCK:
        _YAHOO_NEXT_REQUEST_AT = max(
            _YAHOO_NEXT_REQUEST_AT,
            time.monotonic() + seconds,
        )


def _write_gzip_exclusive(path: Path, content: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("xb") as output:
        with gzip.GzipFile(
            filename="",
            mode="wb",
            fileobj=output,
            compresslevel=6,
            mtime=0,
        ) as compressed:
            compressed.write(content)


def _store_success_payload(
    symbol: str,
    artifact_root: Path,
    target: Path,
    content: bytes,
    attempt: int,
) -> tuple[Path, bool]:
    """Store without overwrite, recovering interrupted writes by exact hash."""
    response_sha256 = hashlib.sha256(content).hexdigest()
    if target.exists():
        with gzip.open(target, "rb") as existing:
            existing_sha256 = hashlib.sha256(existing.read()).hexdigest()
        if existing_sha256 == response_sha256:
            return target, True
        target = (
            artifact_root
            / "raw/chart_versions"
            / f"{symbol}.attempt{attempt}.{time.time_ns()}.json.gz"
        )
    _write_gzip_exclusive(target, content)
    return target, False


def _fetch_one(
    symbol: str,
    artifact_root: Path,
    params: dict[str, Any],
    retries: int,
    rate_interval_seconds: float,
) -> dict[str, Any]:
    url = ENDPOINT.format(symbol=symbol)
    target = artifact_root / "raw/chart" / f"{symbol}.json.gz"
    attempts = []
    for attempt in range(1, retries + 1):
        _yahoo_rate_wait(rate_interval_seconds)
        started = _utc_now()
        try:
            response = _session().get(url, params=params, timeout=45)
            content = response.content
            attempt_record = {"attempt": attempt, "started_at_utc": started, "status_code": response.status_code, "bytes": len(content)}
            attempts.append(attempt_record)
            if response.status_code == 200:
                parsed = response.json()
                chart = parsed.get("chart", {})
                if chart.get("error") is not None or not chart.get("result"):
                    raise ValueError(f"chart_error:{chart.get('error')}")
                stored_path, stored_payload_reused = _store_success_payload(
                    symbol,
                    artifact_root,
                    target,
                    content,
                    attempt,
                )
                return {
                    "symbol": symbol, "status": "success", "request_url": response.url,
                    "request_params": params, "retrieved_at_utc": _utc_now(),
                    "http_status": response.status_code, "response_size_bytes": len(content),
                    "response_sha256": hashlib.sha256(content).hexdigest(),
                    "stored_path": stored_path.relative_to(artifact_root).as_posix(),
                    "stored_size_bytes": stored_path.stat().st_size,
                    "stored_sha256": sha256_file(stored_path),
                    "stored_payload_reused_after_interruption": stored_payload_reused,
                    "response_headers": {k: response.headers.get(k) for k in ("Date", "ETag", "Last-Modified", "Cache-Control", "Age", "Content-Type") if response.headers.get(k)},
                    "attempts": attempts,
                }
            failure_dir = artifact_root / "raw/failures"
            failure_dir.mkdir(parents=True, exist_ok=True)
            failure_path = failure_dir / f"{symbol}.attempt{attempt}.{time.time_ns()}.bin.gz"
            _write_gzip_exclusive(failure_path, content)
            attempt_record.update({
                "response_sha256": hashlib.sha256(content).hexdigest(),
                "stored_path": failure_path.relative_to(artifact_root).as_posix(),
                "stored_size_bytes": failure_path.stat().st_size,
                "stored_sha256": sha256_file(failure_path),
            })
            if response.status_code == 429:
                retry_after = response.headers.get("Retry-After")
                retry_after_seconds = float(retry_after) if retry_after and retry_after.isdigit() else 0.0
                _yahoo_cooldown(max(
                    retry_after_seconds,
                    YAHOO_429_COOLDOWN_SECONDS * attempt,
                ))
            if response.status_code not in {408, 429, 500, 502, 503, 504}:
                break
        except Exception as exc:  # explicit failure is retained; no substitution
            if not attempts or "error" not in attempts[-1]:
                attempts.append({"attempt": attempt, "started_at_utc": started, "error": f"{type(exc).__name__}:{exc}"})
        if attempt < retries:
            time.sleep(min(8, 2 ** (attempt - 1)))
    return {
        "symbol": symbol, "status": "failure", "request_url": url + "?" + urlencode(params),
        "request_params": params, "retrieved_at_utc": _utc_now(), "attempts": attempts,
    }


def fetch(
    artifact_root: Path,
    workers: int,
    retries: int,
    rate_interval_seconds: float = YAHOO_REQUEST_INTERVAL_SECONDS,
) -> None:
    config = json.loads((artifact_root / "configuration/config.json").read_text())
    symbols = json.loads((artifact_root / "checkpoints/symbols.json").read_text())
    manifest_path = artifact_root / "raw/response_manifest.jsonl"
    prior: dict[str, dict] = {}
    if manifest_path.exists():
        for line in manifest_path.read_text().splitlines():
            item = json.loads(line)
            prior[item["symbol"]] = item
    pending = [s for s in symbols if prior.get(s, {}).get("status") != "success"]
    params = config["request_params"]
    with manifest_path.open("a", encoding="utf-8") as out:
        pool = ThreadPoolExecutor(max_workers=workers)
        futures = {
            pool.submit(
                _fetch_one,
                s,
                artifact_root,
                params,
                retries,
                rate_interval_seconds,
            ): s
            for s in pending
        }

        def record(future) -> None:
            item = future.result()
            out.write(json.dumps(item, sort_keys=True) + "\n")
            out.flush()
            os.fsync(out.fileno())

        recorded = set()
        try:
            for future in as_completed(futures):
                record(future)
                recorded.add(future)
        except BaseException:
            for future in futures:
                future.cancel()
            pool.shutdown(wait=True)
            for future in futures:
                if (
                    future not in recorded
                    and future.done()
                    and not future.cancelled()
                ):
                    record(future)
                    recorded.add(future)
            raise
        else:
            pool.shutdown(wait=True)


def _calendar_frame(artifact_root: Path) -> pd.DataFrame:
    frame = pd.read_parquet(artifact_root / "calendar/xnys_regular_sessions.parquet")
    frame["market_open"] = pd.to_datetime(frame["market_open"], utc=True)
    frame["market_close"] = pd.to_datetime(frame["market_close"], utc=True)
    return frame.set_index("session_date")


def normalize(artifact_root: Path) -> None:
    calendar = _calendar_frame(artifact_root)
    latest = {}
    for line in (artifact_root / "raw/response_manifest.jsonl").read_text().splitlines():
        item = json.loads(line)
        latest[item["symbol"]] = item
    results = []
    for symbol in json.loads((artifact_root / "checkpoints/symbols.json").read_text()):
        item = latest.get(symbol)
        if not item or item.get("status") != "success":
            results.append({"symbol": symbol, "status": "unavailable", "reason": "retrieval_failure"})
            continue
        path = artifact_root / item["stored_path"]
        with gzip.open(path, "rt", encoding="utf-8") as f:
            result = json.load(f)["chart"]["result"][0]
        meta = result.get("meta", {})
        returned_symbol = provider_symbol(meta.get("symbol", ""))
        if returned_symbol != symbol:
            results.append({"symbol": symbol, "status": "excluded", "reason": "provider_symbol_mismatch", "returned_symbol": returned_symbol})
            continue
        timestamps = result.get("timestamp") or []
        quote = ((result.get("indicators") or {}).get("quote") or [{}])[0]
        adj = ((result.get("indicators") or {}).get("adjclose") or [{}])[0].get("adjclose")
        close = quote.get("close")
        if not timestamps or adj is None or close is None or len(timestamps) != len(adj) or len(adj) != len(close):
            results.append({"symbol": symbol, "status": "excluded", "reason": "missing_or_misaligned_close_adjclose"})
            continue
        prices = pd.DataFrame({
            "source_timestamp": pd.to_datetime(timestamps, unit="s", utc=True),
            "raw_close": pd.to_numeric(close, errors="coerce"),
            "total_return_close": pd.to_numeric(adj, errors="coerce"),
        })
        prices["session_date"] = prices["source_timestamp"].dt.strftime("%Y-%m-%d")
        prices = prices.merge(calendar.reset_index(), on="session_date", how="left", validate="many_to_one")
        invalid_calendar = int(prices["market_close"].isna().sum())
        prices = prices.dropna(subset=["market_close", "raw_close", "total_return_close"])
        prices = prices[(prices["raw_close"] > 0) & (prices["total_return_close"] > 0)]
        prices = prices.drop_duplicates("session_date", keep=False).sort_values("market_close")
        prices.insert(0, "symbol", symbol)
        if prices.empty:
            results.append({"symbol": symbol, "status": "unavailable", "reason": "no_valid_regular_session_prices"})
            continue
        prices.to_parquet(artifact_root / "normalized/prices" / f"{symbol}.parquet", index=False)
        event_rows = []
        for event_type, payloads in (result.get("events") or {}).items():
            for key, event in payloads.items():
                event_rows.append({"symbol": symbol, "event_type": event_type, "event_key": key, "event_json": json.dumps(event, sort_keys=True)})
        pd.DataFrame(event_rows, columns=["symbol", "event_type", "event_key", "event_json"]).to_parquet(
            artifact_root / "normalized/events" / f"{symbol}.parquet", index=False
        )
        results.append({
            "symbol": symbol, "status": "supported", "reason": None,
            "provider_exchange": meta.get("exchangeName"), "provider_timezone": meta.get("exchangeTimezoneName"),
            "provider_instrument_type": meta.get("instrumentType"), "first_session": prices["session_date"].min(),
            "last_session": prices["session_date"].max(), "regular_session_rows": len(prices),
            "noncalendar_source_rows": invalid_calendar, "event_records": len(event_rows),
        })
    pd.DataFrame(results).to_parquet(artifact_root / "normalized/normalization_summary.parquet", index=False)


def _benchmark_for_market_cap(value: float) -> str:
    if value < 300_000_000:
        return "IWC"
    if value < 2_000_000_000:
        return "IWM"
    if value < 10_000_000_000:
        return "MDY"
    return "SPY"


def _load_prices(artifact_root: Path, symbol: str) -> pd.DataFrame | None:
    path = artifact_root / "normalized/prices" / f"{symbol}.parquet"
    if not path.is_file():
        return None
    frame = pd.read_parquet(path)
    frame["market_close"] = pd.to_datetime(frame["market_close"], utc=True)
    return frame.sort_values("market_close").reset_index(drop=True)


def _common_prices(stock: pd.DataFrame, benchmark: pd.DataFrame) -> pd.DataFrame:
    return stock[["session_date", "market_close", "total_return_close"]].merge(
        benchmark[["session_date", "market_close", "total_return_close"]], on=["session_date", "market_close"], suffixes=("_stock", "_benchmark")
    ).sort_values("market_close").reset_index(drop=True)


def _pick_common(merged: pd.DataFrame, *, after: pd.Timestamp | None = None, on_or_after: pd.Timestamp | None = None, deadline: pd.Timestamp) -> pd.Series | None:
    if after is not None:
        merged = merged[merged["market_close"] > after]
    if on_or_after is not None:
        merged = merged[merged["market_close"] >= on_or_after]
    merged = merged[merged["market_close"] <= deadline]
    return None if merged.empty else merged.iloc[0]


def _first_common(stock: pd.DataFrame, benchmark: pd.DataFrame, *, after: pd.Timestamp | None = None, on_or_after: pd.Timestamp | None = None, deadline: pd.Timestamp) -> pd.Series | None:
    """Compatibility wrapper used by focused tests and small callers."""
    return _pick_common(_common_prices(stock, benchmark), after=after, on_or_after=on_or_after, deadline=deadline)


def materialize_labels(artifact_root: Path) -> None:
    annual = pd.read_parquet(artifact_root / "inputs/certified_annual_population.parquet")
    annual["availability_timestamp"] = pd.to_datetime(annual["availability_timestamp"], utc=True, errors="coerce")
    normalization = pd.read_parquet(artifact_root / "normalized/normalization_summary.parquet").set_index("symbol")
    benchmark_prices = {symbol: _load_prices(artifact_root, symbol) for symbol in BENCHMARKS}
    observed_gate_rows = []
    observed_labels = []
    policy_gate_rows = []
    policy_labels = []
    for ticker, group in annual.groupby("ticker", sort=True):
        symbol = provider_symbol(ticker)
        stock = _load_prices(artifact_root, symbol)
        provider_exchange = normalization.loc[symbol, "provider_exchange"] if symbol in normalization.index else None
        common_by_benchmark = {
            benchmark: _common_prices(stock, prices)
            for benchmark, prices in benchmark_prices.items()
            if stock is not None and prices is not None
        }
        for _, row in group.iterrows():
            base = {
                "entity_id": row["entity_id"], "cik": row["cik"], "ticker": ticker,
                "provider_symbol": symbol, "exchange": row["exchange"],
                "provider_exchange": provider_exchange,
                "exchange_calendar": EXCHANGE_CALENDARS.get(row["exchange"]),
                "fiscal_year": int(row["fiscal_year"]),
            }
            decision_year = int(row["fiscal_year"]) + 1
            cutoff = pd.Timestamp(f"{decision_year}-06-30 23:59:59.999999999", tz="America/New_York").tz_convert("UTC")
            decision = pd.Timestamp(f"{decision_year}-07-02 00:00:00", tz="UTC")
            prediction = pd.Timestamp(f"{decision_year}-07-02 00:01:00", tz="UTC")
            exclusion = None
            if row["market"] != "US" or row["period_type"] != "annual":
                exclusion = "outside_official_us_annual_scope"
            elif row["exchange"] not in EXCHANGE_CALENDARS:
                exclusion = "unsupported_exchange_calendar_mapping"
            elif stock is not None and provider_exchange not in PROVIDER_EXCHANGES[row["exchange"]]:
                exclusion = "provider_exchange_mapping_mismatch"
            elif row["availability_provenance"] != "sec_primary_filing" or pd.isna(row["availability_timestamp"]):
                exclusion = "unsupported_filing_provenance"
            elif row["availability_timestamp"] > cutoff:
                exclusion = "late_filing_after_information_cutoff"
            shares = pd.to_numeric(pd.Series([row["shares_outstanding"]]), errors="coerce").iloc[0]
            unavailable = None
            market_cap = np.nan
            benchmark_symbol = None
            if exclusion is None:
                if stock is None:
                    unavailable = "stock_mapping_or_price_payload_unavailable"
                elif pd.isna(shares) or shares <= 0:
                    unavailable = "decision_available_shares_unavailable"
                else:
                    prior = stock[stock["market_close"] < decision]
                    prior = prior[prior["market_close"] >= decision - pd.Timedelta(days=5)]
                    if prior.empty:
                        unavailable = "predecision_stock_close_unavailable"
                    else:
                        market_cap = float(prior.iloc[-1]["raw_close"] * shares)
                        benchmark_symbol = _benchmark_for_market_cap(market_cap)
                        if benchmark_prices[benchmark_symbol] is None:
                            unavailable = "assigned_benchmark_payload_unavailable"
            for horizon, months in HORIZONS.items():
                gate = {**base, "horizon": horizon, "decision_timestamp": decision, "prediction_timestamp": prediction, "information_cutoff": cutoff, "benchmark_symbol": benchmark_symbol, "decision_market_cap": market_cap}
                label = None
                reason = exclusion or unavailable
                classification = "excluded" if exclusion else ("unavailable" if unavailable else None)
                if classification is None:
                    common = common_by_benchmark[benchmark_symbol]
                    entry = _pick_common(common, after=prediction, deadline=prediction + pd.Timedelta(days=5))
                    if entry is None:
                        classification, reason = "unavailable", "common_entry_session_unavailable"
                    else:
                        target = entry["market_close"] + pd.DateOffset(months=months)
                        exit_row = _pick_common(common, on_or_after=target, deadline=target + pd.Timedelta(days=10))
                        if exit_row is None:
                            classification, reason = "unavailable", "common_exit_session_unavailable"
                        else:
                            classification, reason = "supported", None
                            stock_return = float(exit_row["total_return_close_stock"] / entry["total_return_close_stock"] - 1)
                            benchmark_return = float(exit_row["total_return_close_benchmark"] / entry["total_return_close_benchmark"] - 1)
                            label = {
                                **gate, "entry_session": entry["session_date"], "entry_timestamp": entry["market_close"],
                                "exit_session": exit_row["session_date"], "label_end_date": exit_row["market_close"],
                                "stock_entry_total_return_close": float(entry["total_return_close_stock"]),
                                "stock_exit_total_return_close": float(exit_row["total_return_close_stock"]),
                                "benchmark_entry_total_return_close": float(entry["total_return_close_benchmark"]),
                                "benchmark_exit_total_return_close": float(exit_row["total_return_close_benchmark"]),
                                "stock_return": stock_return, "benchmark_return": benchmark_return,
                                "relative_return": stock_return - benchmark_return,
                                "outperformed_benchmark": bool(stock_return > benchmark_return),
                                "label_provenance": "observed_common_session_provider_adjclose",
                            }
                            observed_labels.append(label)
                            policy_labels.append({**label, "population": "include_policy_imputed", "policy_imputed": False})
                gate.update({"classification": classification, "reason": reason})
                observed_gate_rows.append({**gate, "population": "observed_only"})
                policy_gate_rows.append({**gate, "population": "include_policy_imputed", "policy_imputed": False})
    observed = pd.DataFrame(observed_labels)
    if not observed.empty:
        observed["population"] = "observed_only"
        observed["policy_imputed"] = False
    pd.DataFrame(observed_gate_rows).to_parquet(artifact_root / "support/observed_only_row_horizon.parquet", index=False)
    pd.DataFrame(policy_gate_rows).to_parquet(artifact_root / "support/include_policy_imputed_row_horizon.parquet", index=False)
    observed.to_parquet(artifact_root / "outputs/observed_only/labels.parquet", index=False)
    pd.DataFrame(policy_labels, columns=list(observed.columns) if not observed.empty else None).to_parquet(
        artifact_root / "outputs/include_policy_imputed/labels.parquet", index=False
    )
    summaries = []
    for population, rows in (("observed_only", observed_gate_rows), ("include_policy_imputed", policy_gate_rows)):
        frame = pd.DataFrame(rows)
        for horizon in HORIZONS:
            counts = frame.loc[frame["horizon"].eq(horizon), "classification"].value_counts().to_dict()
            summaries.append({
                "population": population, "horizon": horizon, "candidate_rows": int((frame["horizon"] == horizon).sum()),
                "supported": int(counts.get("supported", 0)), "unavailable": int(counts.get("unavailable", 0)),
                "excluded": int(counts.get("excluded", 0)), "policy_imputed_supported": 0,
                "verdict": "supported" if counts.get("supported", 0) else "unsupported",
            })
    pd.DataFrame(summaries).to_parquet(artifact_root / "support/horizon_support.parquet", index=False)


def _record(base: Path, path: Path, role: str) -> dict[str, Any]:
    return {"path": path.relative_to(base).as_posix(), "role": role, "size_bytes": path.stat().st_size, "sha256": sha256_file(path)}


def freeze(root: Path, artifact_root: Path) -> None:
    response_path = artifact_root / "raw/response_manifest.jsonl"
    latest = {}
    for line in response_path.read_text().splitlines():
        item = json.loads(line)
        latest[item["symbol"]] = item
    raw_errors = []
    raw_records = []
    for symbol, item in sorted(latest.items()):
        if item.get("status") != "success":
            continue
        path = artifact_root / item["stored_path"]
        if path.stat().st_size != item["stored_size_bytes"] or sha256_file(path) != item["stored_sha256"]:
            raw_errors.append(symbol)
            continue
        with gzip.open(path, "rb") as f:
            payload = f.read()
        if len(payload) != item["response_size_bytes"] or hashlib.sha256(payload).hexdigest() != item["response_sha256"]:
            raw_errors.append(symbol)
        raw_records.append(_record(artifact_root, path, "raw_chart_response"))
    if raw_errors:
        raise RuntimeError(f"raw hash failures: {raw_errors[:10]}")
    successful_raw_count = len(raw_records)
    raw_inventory = artifact_root / "raw/raw_inventory.json"
    for path in sorted((artifact_root / "raw/failures").glob("*.gz")) if (artifact_root / "raw/failures").exists() else []:
        raw_records.append(_record(artifact_root, path, "raw_failure_response"))
    raw_inventory.write_text(json.dumps(raw_records, indent=2) + "\n")

    normalized_records = []
    for directory, role in (("normalized/prices", "normalized_regular_session_prices"), ("normalized/events", "normalized_provider_events")):
        for path in sorted((artifact_root / directory).glob("*.parquet")):
            normalized_records.append(_record(artifact_root, path, role))
    normalized_inventory = artifact_root / "normalized/normalized_inventory.json"
    normalized_inventory.write_text(json.dumps(normalized_records, indent=2) + "\n")

    status_path = artifact_root / "lineage/git_status_porcelain.txt"
    patch_path = artifact_root / "lineage/tracked_dirty.patch"
    untracked_path = artifact_root / "lineage/untracked_inventory.json"
    status_path.write_bytes(subprocess.check_output(["git", "status", "--porcelain=v1", "--untracked-files=all"], cwd=root))
    patch_path.write_bytes(subprocess.check_output(["git", "diff", "--binary", "3f706e3e10d2b354c6e8b9407760fa2074749c0a", "--", "."], cwd=root))
    untracked = []
    for raw in subprocess.check_output(["git", "ls-files", "--others", "--exclude-standard", "-z"], cwd=root).split(b"\0"):
        if not raw:
            continue
        path = root / os.fsdecode(raw)
        if path.is_file() and path not in {artifact_root / "manifest.json", untracked_path}:
            untracked.append(_record(root, path, "untracked_dirty_state"))
    untracked_path.write_text(json.dumps(untracked, indent=2) + "\n")

    support = pd.read_parquet(artifact_root / "support/horizon_support.parquet")
    required_outputs = [
        artifact_root / "inputs/certified_annual_population.parquet",
        artifact_root / "inputs/security_mapping.parquet",
        artifact_root / "inputs/session8b_calendar_contract.json",
        artifact_root / "configuration/config.json",
        artifact_root / "calendar/xnys_regular_sessions.parquet",
        artifact_root / "calendar/xnas_regular_sessions.parquet",
        artifact_root / "calendar/calendar_evidence.json",
        response_path, raw_inventory,
        artifact_root / "checkpoints/symbols.json",
        artifact_root / "normalized/normalization_summary.parquet",
        normalized_inventory,
        artifact_root / "support/observed_only_row_horizon.parquet",
        artifact_root / "support/include_policy_imputed_row_horizon.parquet",
        artifact_root / "support/horizon_support.parquet",
        artifact_root / "outputs/observed_only/labels.parquet",
        artifact_root / "outputs/include_policy_imputed/labels.parquet",
        status_path, patch_path, untracked_path,
    ]
    code_paths = [root / "pipeline/build_contract_label_inputs.py", root / "tests/pipeline/test_build_contract_label_inputs.py"]
    manifest = {
        "schema_version": 1, "artifact_class": "SESSION8E_CONTRACT_ALIGNED_LABEL_INPUTS",
        "created_at_utc": _utc_now(), "baseline_commit": "3f706e3e10d2b354c6e8b9407760fa2074749c0a",
        "current_head": subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=root, text=True).strip(),
        "claim": {"contract_aligned_labels_generated": True, "models_predictions_backtests_generated": False, "session9_allowed": bool((support["supported"] > 0).any())},
        "validated_inputs": [
            {"path": "artifacts/pit_validation/corrected_step2/manifest.json", "sha256": STEP2_MANIFEST_SHA256},
            {"path": "artifacts/pit_validation/calendar_contract/session8b_calendar_contract.json", "sha256": CALENDAR_CONTRACT_SHA256},
        ],
        "configuration": json.loads((artifact_root / "configuration/config.json").read_text()),
        "records": [_record(root, path, "session8e_evidence_or_output") for path in required_outputs],
        "code_lineage": [_record(root, path, "session8e_code_or_test") for path in code_paths],
        "raw_payloads": {"successful": successful_raw_count, "failed": sum(x.get("status") != "success" for x in latest.values()), "all_success_hashes_verified": True},
        "environment": {
            "python": sys.version,
            "dependencies": {name: importlib.metadata.version(name) for name in ("pandas", "pyarrow", "requests", "exchange-calendars")},
        },
        "dirty_state": {"complete_status_recorded": True, "baseline": "3f706e3e10d2b354c6e8b9407760fa2074749c0a", "manifest_self_excluded": "artifacts/pit_validation/contract_aligned_label_inputs/manifest.json"},
        "support_verdicts": support.to_dict(orient="records"),
        "population_separation": {"observed_only": "outputs/observed_only", "include_policy_imputed": "outputs/include_policy_imputed", "policy_only_additions": 0},
        "limitations": [
            "Yahoo chart is a frozen provider payload, not an official exchange feed.",
            "Retrieval timestamp certifies the frozen retrieval vintage, not an unavailable historical vendor revision vintage.",
            "No unsupported security mapping, missing price, missing session, missing benchmark, or corporate-action outcome is inferred.",
            "Provider adjusted close is the sole total-return input; preserved events are not added separately.",
        ],
    }
    (artifact_root / "manifest.json").write_text(json.dumps(manifest, indent=2, default=str) + "\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("init", "calendar", "fetch", "normalize", "labels", "freeze"))
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--artifact-root", type=Path, required=True)
    parser.add_argument("--end-date-exclusive", default=(pd.Timestamp.now(tz="UTC").normalize() + pd.Timedelta(days=1)).strftime("%Y-%m-%d"))
    parser.add_argument("--workers", type=int, default=4)
    parser.add_argument("--retries", type=int, default=3)
    args = parser.parse_args()
    root, artifact_root = args.root.resolve(), args.artifact_root.resolve()
    if args.command == "init": initialize(root, artifact_root, args.end_date_exclusive)
    elif args.command == "calendar": freeze_calendar(artifact_root)
    elif args.command == "fetch": fetch(artifact_root, args.workers, args.retries)
    elif args.command == "normalize": normalize(artifact_root)
    elif args.command == "labels": materialize_labels(artifact_root)
    elif args.command == "freeze": freeze(root, artifact_root)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
