from __future__ import annotations

import subprocess
import sys

import pandas as pd
import plotly.express as px
import streamlit as st

from src.config import BASE, STRAT_FILES
from src.leverage import (
    MAX_BENEISH, MAX_LEVERAGE, MAX_POSITION_PCT, MIN_ALTMAN_Z,
    MIN_PIOTROSKI, build_short_book, size_positions,
)


def tab_strategies(df_all: pd.DataFrame | None = None,
                   models: dict | None = None,
                   meta: dict | None = None) -> None:
    st.header('🎯 High-ROI Strategy Picks')

    # ── Existing strategy CSVs ──────────────────────────────────────────────
    st.subheader('Screener-Based Picks (QEM / SCDV / IARB)')
    st.caption('Generated by `scripts/high_roi_strategies.py`. Re-run to refresh picks.')

    col_run, col_cap = st.columns([1, 2])
    with col_run:
        run_strats = st.button('▶ Run / Refresh Strategies', type='primary')
    with col_cap:
        capital = st.number_input('Portfolio capital (€)', value=10_000,
                                  min_value=1_000, step=1_000, key='strat_capital')

    if run_strats:
        with st.spinner('Running strategy screener (30–60s)…'):
            res = subprocess.run(
                [sys.executable, str(BASE / 'scripts' / 'high_roi_strategies.py'),
                 '--strategy', 'all', '--capital', str(capital)],
                capture_output=True, text=True, cwd=str(BASE),
            )
        if res.returncode == 0:
            st.success('Strategies refreshed!')
        else:
            st.error(f'Strategy script failed:\n{res.stderr[-1000:]}')
            return

    any_found = False
    for label, path in STRAT_FILES.items():
        if not path.exists():
            continue
        any_found = True
        st.subheader(label)
        df_s = pd.read_csv(path)
        score_col = next((c for c in df_s.columns if c.endswith('_score')), None)

        n = len(df_s)
        k1, k2, k3, k4 = st.columns(4)
        k1.metric('Picks', n)
        if score_col and df_s[score_col].notna().any():
            k2.metric('Top score', f'{df_s[score_col].max():.3f}')
        if 'market_cap_at_filing' in df_s.columns:
            med_cap = df_s['market_cap_at_filing'].median()
            k3.metric('Median mkt cap',
                      f'${med_cap/1e9:.1f}B' if pd.notna(med_cap) and med_cap >= 1e9
                      else (f'${med_cap/1e6:.0f}M' if pd.notna(med_cap) else 'N/A'))
        if capital and n > 0:
            k4.metric('Pos size (EW)', f'€{capital/n:,.0f}')

        st.dataframe(df_s, use_container_width=True, height=300)

        if score_col and df_s[score_col].notna().any():
            fig = px.bar(
                df_s.head(20), x=score_col,
                y='ticker' if 'ticker' in df_s.columns else df_s.columns[0],
                orientation='h', color=score_col, color_continuous_scale='Blues',
                title=f'Top {min(n, 20)} picks by score',
            )
            fig.update_layout(height=320, margin=dict(t=40, b=10), showlegend=False)
            st.plotly_chart(fig, use_container_width=True)

        st.download_button(
            f'⬇️ Download {label.split("—")[0].strip()} CSV',
            df_s.to_csv(index=False),
            path.name, 'text/csv',
            key=f'dl_{path.stem}',
        )
        st.divider()

    if not any_found:
        st.info('No strategy CSVs found. Click **Run / Refresh Strategies** above.')

    # ── Leverage Strategy (Long / Short) ────────────────────────────────────
    st.markdown('---')
    st.subheader('📐 Leverage Strategy  ·  Long Fraud-Safe / Short High-Beneish')
    st.caption(
        'Half-Kelly position sizing capped at 2× notional. '
        'Quality gates: Piotroski F ≥ 6, Beneish M < −1.78, Altman Z > 1.81.'
    )

    if df_all is None or df_all.empty:
        st.info('No dataset loaded.')
        return

    lev_col1, lev_col2, lev_col3 = st.columns(3)
    with lev_col1:
        lev_capital = st.number_input('Capital (€)', value=10_000,
                                      min_value=1_000, step=1_000,
                                      key='lev_capital')
    with lev_col2:
        markets = sorted(df_all['market'].dropna().unique().tolist())
        lev_market = st.selectbox('Market', ['All'] + markets, key='lev_market')
    with lev_col3:
        lev_top = st.slider('Long positions', min_value=5, max_value=50,
                            value=20, key='lev_top')

    run_lev = st.button('▶ Build Long / Short Portfolio', key='run_lev')
    if not run_lev:
        return

    # Filter to latest fiscal year per ticker in the selected market
    df_lev = df_all.copy()
    if lev_market != 'All':
        df_lev = df_lev[df_lev['market'] == lev_market]

    if df_lev.empty:
        st.warning('No data for this market.')
        return

    df_lev = (df_lev.sort_values('fiscal_year', ascending=False)
              .drop_duplicates('ticker', keep='first')
              .reset_index(drop=True))

    # Use composite_score if present; otherwise use fraud_score_composite
    if 'composite_score' not in df_lev.columns:
        if 'fraud_score_composite' in df_lev.columns:
            df_lev['composite_score'] = df_lev['fraud_score_composite']
        else:
            st.warning('No composite_score column in dataset.')
            return

    with st.spinner('Sizing positions…'):
        positions = size_positions(df_lev, lev_top, lev_capital)
        shorts    = build_short_book(df_lev, top_n=10, capital=lev_capital)

    # ── Summary KPIs ────────────────────────────────────────────────────────
    total_invested = positions['position_€'].sum()
    total_notional = positions['notional_€'].sum()
    safe_count     = int(positions['leverage_safe'].sum())

    m1, m2, m3, m4 = st.columns(4)
    m1.metric('Long positions', len(positions))
    m2.metric('Leverage-safe', f'{safe_count}/{len(positions)}')
    m3.metric('Capital invested', f'€{total_invested:,.0f}')
    m4.metric('Notional exposure',
              f'€{total_notional:,.0f}',
              delta=f'{total_notional/lev_capital:.2f}× of capital')

    # ── Long book table ──────────────────────────────────────────────────────
    st.markdown('**Long Book**')
    disp_cols = [c for c in ['ticker', 'name', 'composite_score', 'leverage_safe',
                              'position_pct', 'position_€', 'leverage_mult',
                              'notional_€', 'piotroski_f', 'beneish_m', 'ml_1y', 'strategy']
                 if c in positions.columns]

    def _style_safe(val):
        return 'background-color: #1b5e20; color: white' if val == 1 else 'background-color: #b71c1c; color: white'

    st.dataframe(
        positions[disp_cols].style.applymap(_style_safe, subset=['leverage_safe'])
        if 'leverage_safe' in disp_cols else positions[disp_cols],
        use_container_width=True, hide_index=True,
    )

    # Bar chart: position notional by ticker
    fig_long = px.bar(
        positions, x='ticker', y='notional_€',
        color='leverage_safe', color_discrete_map={1: '#2e7d32', 0: '#c62828'},
        title='Notional exposure per ticker (green = leverage-safe)',
        labels={'notional_€': 'Notional (€)', 'leverage_safe': 'Safe'},
    )
    fig_long.update_layout(height=340, margin=dict(t=40, b=20), showlegend=True)
    st.plotly_chart(fig_long, use_container_width=True)

    st.download_button(
        '⬇️ Download long book CSV',
        positions.to_csv(index=False), 'leverage_long.csv', 'text/csv',
        key='dl_long',
    )

    # ── Short book ───────────────────────────────────────────────────────────
    st.markdown('---')
    st.markdown('**Short Book**  (Beneish M > −1.78, market cap > $100M)')
    if shorts.empty:
        st.info('No short candidates passed the Beneish threshold in this market/year.')
    else:
        short_capital = shorts['short_€'].sum() if 'short_€' in shorts.columns else 0
        s1, s2 = st.columns(2)
        s1.metric('Short positions', len(shorts))
        s2.metric('Gross short exposure', f'€{short_capital:,.0f}')

        st.dataframe(shorts, use_container_width=True, hide_index=True)
        st.download_button(
            '⬇️ Download short book CSV',
            shorts.to_csv(index=False), 'leverage_short.csv', 'text/csv',
            key='dl_short',
        )

    # ── Risk rules expander ──────────────────────────────────────────────────
    with st.expander('⚙️ Risk Rules & Strategy Guide', expanded=False):
        st.markdown(f"""
| Parameter | Value |
|---|---|
| Half-Kelly fraction | {0.5} |
| Max single position | {MAX_POSITION_PCT*100:.0f}% |
| Max leverage | {MAX_LEVERAGE}× |
| Min Piotroski F | {MIN_PIOTROSKI} |
| Max Beneish M (long) | {MAX_BENEISH} |
| Min Altman Z (long) | {MIN_ALTMAN_Z} |
| Short book size | 30% of capital, max 5% per name |

**LEAPS calls** — Buy 12–18mo deep ITM calls (delta ~0.70). Defined-risk 3–5× leverage.
Best for: high-conviction, large-cap names with ML 1y score ≥ 0.75.

**2:1 margin long** — Reg-T margin (IBKR). Borrow ~5.8% p.a. Return hurdle: stock must beat 5.8%.
Best for: medium conviction, liquid stocks.

**Short (Beneish > −1.78)** — Borrow & sell; await accounting fraud revelation or mean-reversion.
Only applied to names with market cap > $100M (borrow availability).
""")
