from __future__ import annotations

import subprocess
import sys

import pandas as pd
import streamlit as st

from src.config import BASE, STRAT_FILES


def tab_strategies() -> None:
    st.header('🎯 High-ROI Strategy Picks')
    st.caption('Generated by `scripts/high_roi_strategies.py`. Re-run to refresh picks.')

    col_run, col_cap = st.columns([1, 2])
    with col_run:
        run_strats = st.button('▶ Run / Refresh Strategies', type='primary')
    with col_cap:
        capital = st.number_input('Portfolio capital (€)', value=10000, min_value=1000, step=1000)

    if run_strats:
        with st.spinner('Running strategy screener (30–60s)…'):
            res = subprocess.run(
                [sys.executable, str(BASE / 'scripts' / 'high_roi_strategies.py'),
                 '--strategy', 'all', '--capital', str(capital)],
                capture_output=True, text=True, cwd=str(BASE)
            )
        if res.returncode == 0:
            st.success('Strategies refreshed!')
        else:
            st.error(f'Strategy script failed:\n{res.stderr[-1000:]}')
            return

    any_found = False
    for label, path in STRAT_FILES.items():
        if not path.exists():
            continue
        any_found = True
        st.subheader(label)
        df_s = pd.read_csv(path)

        score_col = next((c for c in df_s.columns if c.endswith('_score')), None)

        n = len(df_s)
        k1, k2, k3, k4 = st.columns(4)
        k1.metric('Picks', n)
        if score_col and df_s[score_col].notna().any():
            k2.metric('Top score', f'{df_s[score_col].max():.3f}')
        if 'market_cap_at_filing' in df_s.columns:
            med_cap = df_s['market_cap_at_filing'].median()
            k3.metric('Median market cap',
                      f'${med_cap/1e9:.1f}B' if pd.notna(med_cap) and med_cap >= 1e9
                      else (f'${med_cap/1e6:.0f}M' if pd.notna(med_cap) else 'N/A'))
        if capital and n > 0:
            k4.metric('Position size (equal-weight)', f'€{capital/n:,.0f}')

        st.dataframe(df_s, use_container_width=True, height=300)

        if score_col and df_s[score_col].notna().any():
            import matplotlib.pyplot as plt
            fig, ax = plt.subplots(figsize=(8, 2.5))
            ax.barh(range(min(n, 20)), df_s[score_col].head(20), color='#2196F3', edgecolor='white')
            if 'ticker' in df_s.columns:
                ax.set_yticks(range(min(n, 20)))
                ax.set_yticklabels(df_s['ticker'].head(20), fontsize=8)
            ax.set_xlabel('Score')
            ax.set_title(f'Top {min(n, 20)} picks by score')
            ax.grid(axis='x', alpha=0.3)
            plt.tight_layout()
            st.pyplot(fig, use_container_width=True)
            plt.close()

        st.download_button(f'⬇️ Download {label.split("—")[0].strip()} CSV',
                           df_s.to_csv(index=False),
                           path.name, 'text/csv',
                           key=f'dl_{path.stem}')
        st.divider()

    if not any_found:
        st.info('No strategy CSVs found. Click **Run / Refresh Strategies** above.')
